# Generated by Django 3.0.3 on 2020-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('shop', '0001_initial'), ('shop', '0002_product_image'), ('shop', '0003_contact'), ('shop', '0004_user_userlogin'), ('shop', '0005_auto_20200418_0333'), ('shop', '0006_auto_20200418_2024')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(default='', max_length=50)),
                ('contact_email', models.CharField(default='', max_length=50)),
                ('contact_phoneno', models.CharField(default='', max_length=50)),
                ('contact_msg', models.CharField(default='', max_length=50)),
                ('contact_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=50)),
                ('user_phone', models.CharField(default='', max_length=20)),
                ('user_add1', models.CharField(default='', max_length=100)),
                ('user_add2', models.CharField(default='', max_length=100)),
                ('user_city', models.CharField(default='', max_length=20)),
                ('user_state', models.CharField(default='', max_length=20)),
                ('user_pincode', models.CharField(default='', max_length=10)),
                ('user_email', models.CharField(default='', max_length=80)),
                ('user_sq1', models.CharField(default='', max_length=50)),
                ('user_sq1ans', models.CharField(default='', max_length=50)),
                ('user_sq2', models.CharField(default='', max_length=50)),
                ('user_sq2ans', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(default='', max_length=80)),
                ('user_pass', models.CharField(default='', max_length=10)),
                ('user_loggedin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_desc', models.CharField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('product_id', models.AutoField(default='-1', primary_key=True, serialize=False)),
            ],
        ),
    ]
