# Generated by Django 3.0.3 on 2020-03-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(default='', max_length=50)),
                ('contact_email', models.CharField(default='', max_length=50)),
                ('contact_phoneno', models.CharField(default='', max_length=50)),
                ('contact_msg', models.CharField(default='', max_length=50)),
                ('contact_rate', models.IntegerField(default=0)),
            ],
        ),
    ]
