# Generated by Django 3.0.3 on 2020-04-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_user_userlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_pass',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='user_loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
